### PR TITLE
Be able to specify gitlab version

### PR DESCRIPTION
**Pull request by kostyrev**
Hello, Sam!
I'd like to be able to specify gitlab version to install.
This MR provides such ability. Hope, you'll find it useful.

### CODE REVIEW

**Comment by samdoran** [comment]
Thanks for the added feature!

**Comment by samdoran** [comment]
@kostyrevaa I had to do some extra work to get this working properly for RHEL _and_ Debian. I'll be pushing those changes up shortly.

**Comment by kostyrev** [comment]
BTW, it took 4 months to get it merged.
kinda sad.

**Comment by samdoran** [comment]
I completely agree. Terribly sorry about that. I will do better in the future.

**Pull request merged**
